export const governorates = [
  { value: "Alexandria", label: "Alexandria" },
  { value: "Aswan", label: "Aswan" },
  { value: "Asyut", label: "Asyut" },
  { value: "Beheira", label: "Beheira" },
  { value: "Beni_Suef", label: "Beni Suef" },
  { value: "Cairo", label: "Cairo" },
  { value: "Dakahlia", label: "Dakahlia" },
  { value: "Damietta", label: "Damietta" },
  { value: "Faiyum", label: "Faiyum" },
  { value: "Gharbia", label: "Gharbia" },
  { value: "Giza", label: "Giza" },
  { value: "Ismailia", label: "Ismailia" },
  { value: "Kafr_El_Sheikh", label: "Kafr El Sheikh" },
  { value: "Luxor", label: "Luxor" },
  { value: "Matruh", label: "Matruh" },
  { value: "Minya", label: "Minya" },
  { value: "Monufia", label: "Monufia" },
  { value: "New_Valley", label: "New Valley" },
  { value: "North_Sinai", label: "North Sinai" },
  { value: "Port_Said", label: "Port Said" },
  { value: "Qalyubia", label: "Qalyubia" },
  { value: "Qena", label: "Qena" },
  { value: "Red_Sea", label: "Red Sea" },
  { value: "Sharqia", label: "Sharqia" },
  { value: "Sohag", label: "Sohag" },
  { value: "South_Sinai", label: "South Sinai" },
  { value: "Suez", label: "Suez" },
];
export const categories = [
  {
    label: "PC Parts",
    options: [
      { value: "bundle", label: "bundle" },
      { value: "motherboard,motherboardIntel,motherboardAmd", label: "motherboard" },
      { value: "cpu,cpuAmd,cpuIntel", label: "cpu" },
      { value: "gpu", label: "gpu" },
      { value: "gpuUsed", label: "gpu used" },
      { value: "ram", label: "ram" },
      { value: "ramUsed", label: "ram used" },
      { value: "caseCombo", label: "case+psu combo" },
      { value: "case", label: "case" },
      { value: "psu", label: "psu" },
      { value: "psuUsed", label: "psu used" },
      { value: "monitor", label: "monitor" },
      { value: "monitorUsed", label: "monitor used" },
      { value: "cooling,cpuCooler,airCooler,liquidCooler,thermalPaste,caseFan", label: "COOLING (ALL)" },
      { value: "cpuCooler,airCooler,liquidCooler", label: "cpu cooler (air+liquid)" },
      { value: "airCooler", label: "air cooler" },
      { value: "caseFan", label: "case fan" },
      { value: "liquidCooler", label: "liquid cooler" },
      { value: "thermalPaste", label: "thermal paste" },
      { value: "fanHub", label: "fan hub" },
    ],
  },
  {
    label: "Laptop",
    options: [
      { value: "laptop", label: "laptop" },
      { value: "laptopUsed,laptopOpenBox", label: "laptop used" },
      { value: "laptopBag", label: "laptop bag" },
      { value: "laptopRam", label: "laptop ram" },
      { value: "laptopBattery", label: "laptop battery" },
      { value: "laptopCharger", label: "laptop charger" },
      { value: "laptopStand", label: "laptop stand" },
      { value: "laptopFan", label: "laptop fan" },
    ],
  },
  {
    label: "Storage",
    options: [
      { value: "storage,ssd,ssdSata,ssdM2,hdd", label: "STORAGE (ALL)" },
      { value: "storageUsed,hddUsed", label: "STORAGE USED (ALL)" },
      { value: "ssd,ssdSata,ssdM2", label: "ssd (sata+m.2)" },
      { value: "ssdSata", label: "ssd sata" },
      { value: "ssdM2", label: "ssd m.2" },
      { value: "hdd", label: "hdd" },
      { value: "hddUsed", label: "hdd used" },
      { value: "memoryCard", label: "memory card" },
      { value: "flashDrives", label: "flash drives" },
      { value: "externalStorage", label: "external storage" },
      { value: "rack", label: "rack" },
    ],
  },
  {
    label: "Accessories",
    options: [
      {
        value:
          "accessories,keyboardMouseCombo,keyboard,wirelessKeyboard,mouse,wirelessMouse,mousePad,headphone,webcam,microphone,speaker,gamepad,dongle,cable,converter",
        label: "ACCESSORIES (ALL)",
      },
      { value: "keyboardMouseCombo", label: "keyboard+mouse combo" },
      { value: "keyboard,wirelessKeyboard", label: "keyboard" },
      { value: "mouse,wirelessMouse", label: "mouse" },
      { value: "mousePad", label: "mousepad" },
      { value: "headphone", label: "headphone" },
      { value: "webcam", label: "webcam" },
      { value: "microphone", label: "microphone" },
      { value: "speaker", label: "speaker" },
      { value: "gamepad", label: "gamepad" },
      { value: "dongle", label: "dongle" },
      { value: "cable,converter", label: "cable/converter" },
    ],
  },
  {
    label: "Touch Devices",
    options: [
      { value: "mobilePhone", label: "mobile phone" },
      { value: "tablet", label: "tablet" },
      { value: "graphicTablet", label: "graphic tablet" },
      {
        value: "phoneAccessories,smartwatch,powerbank,mobileCharger,carCharger,holder,pen,earphone,earbuds",
        label: "PHONE ACCESSORIES (ALL)",
      },
      { value: "smartwatch", label: "smartwatch" },
      { value: "powerbank", label: "powerbank" },
      { value: "mobileCharger", label: "mobile charger" },
      { value: "carCharger", label: "car charger" },
      { value: "holder", label: "holder" },
      { value: "pen", label: "pen" },
      { value: "earphone", label: "earphone" },
      { value: "earbuds", label: "earbuds" },
    ],
  },
  {
    label: "Console",
    options: [
      { value: "gamingConsole", label: "gaming console" },
      { value: "consoleCharger", label: "console charger" },
      { value: "consoleAccount", label: "console account" },
      { value: "games", label: "games" },
    ],
  },
  {
    label: "Apple",
    options: [
      { value: "macbook", label: "macbook" },
      { value: "iphone", label: "iphone" },
      { value: "ipad", label: "ipad" },
      { value: "appleWatch", label: "apple watch" },
      { value: "airpod", label: "airpod" },
      { value: "applePencil", label: "apple pencil" },
      { value: "appleAdaptor", label: "apple adaptor" },
      { value: "airtag", label: "airtag" },
    ],
  },
  {
    label: "Networking",
    options: [
      { value: "network,networkCard,router,switch,accesspoint", label: "NETWORK (ALL)" },
      { value: "networkCard", label: "network card" },
      { value: "router", label: "router" },
      { value: "switch", label: "switch" },
      { value: "accesspoint", label: "accesspoint" },
    ],
  },
  {
    label: "Miscellaneous",
    options: [
      { value: "software", label: "software" },
      { value: "cleaning", label: "cleaning" },
      { value: "ups", label: "ups" },
      { value: "powerStrip", label: "power strip" },
      { value: "battery", label: "battery" },
      { value: "tvBox", label: "tvBox" },
      { value: "printer_scanner", label: "printer/scanner" },
      { value: "catridge", label: "catridge" },
      { value: "barcode", label: "barcode" },
      { value: "projector", label: "projector" },
      { value: "presenter", label: "presenter" },
      { value: "surveillance", label: "surveillance/security cameras" },
      { value: "photography", label: "photography" },
      { value: "wallet", label: "wallet" },
      { value: "other", label: "other" },
    ],
  },
];
export const comboboxStyle = {
  control: (baseStyles, state) => {
    return {
      ...baseStyles,
      border: state.menuIsOpen ? "2px solid var(--light-green)" : "2px solid hsl(0, 0%, 90%)",
      borderRadius: "6px",
      "&:hover": {
        borderColor: "var(--light-green)",
      },
    };
  },
  option: (baseStyles, state) => {
    return {
      ...baseStyles,
      color: state.isFocused ? "white" : "black",
      backgroundColor: state.isFocused ? "var(--light-green)" : "white",
    };
  },
};
